/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/metacubex/mihomo/openharmony_bridge */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>

typedef int (*protect_fn)(int);

static inline int call_protect_fn(protect_fn fn, int fd) {
	if (fn == NULL) {
		return 0;
	}
	return fn(fd);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* MihomoOhosVersion();
extern int MihomoOhosPing();
extern void MihomoOhosSetProtectBridge(void* fn);
extern int MihomoOhosEnableProtectHook();
extern int MihomoOhosDisableProtectHook();
extern int MihomoOhosIsRunning();
extern int MihomoOhosStartConfig(char* homeDir, char* configBytes, int configLen);
extern int MihomoOhosStartConfigFile(char* homeDir, char* configPath);
extern int MihomoOhosStartConfigFileWithTunFd(char* homeDir, char* configPath, int tunFd);
extern int MihomoOhosStop();

// MihomoOhosGracefulStop transitions mihomo to a no-TUN, no-DNS, direct-mode
// config. This causes mihomo to drain its TUN reader, DNS resolver, and
// outbound dialer goroutines naturally, after which the caller can safely
// close the TUN fd (via VpnConnection.destroy).
//
// This avoids the SIGSEGV risk of calling MihomoOhosStop while mihomo
// goroutines are still actively using the fd-backed TUN.
//
extern int MihomoOhosGracefulStop();
extern char* MihomoOhosProxyDelay(char* nodeName, char* testURL, int timeoutMs);
extern char* MihomoOhosGroupDelay(char* groupName, char* testURL, int timeoutMs);
extern char* MihomoOhosTrafficStats();
extern int MihomoOhosStartTrafficStatsWriter(char* statsPath);
extern int MihomoOhosStopTrafficStatsWriter();
extern char* MihomoOhosLastError();
extern void MihomoOhosFreeCString(char* s);

#ifdef __cplusplus
}
#endif
